name: CI/CD

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: corepack enable
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn
    - name: Run lint
      run: yarn lint
    - name: Run type check
      run: yarn typecheck
    - name: Run tests
      run: yarn test
    - name: Build
      run: yarn build
